"use client";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createContext, useContext, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const CountContext = createContext<number | null>(null);
export const ThemeContext = createContext<boolean | string | null>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [count, setCount] = useState(0);

  const [theme, setTheme] = useState("light");
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext.Provider value={theme}>
          <>
            <label>
              <input
                type="checkbox"
                checked={theme === "dark"}
                onChange={(e) => {
                  console.dir(e.target.checked);
                  setTheme(e.target.checked ? "dark" : "light");
                }}
              />
              Use dark mode
            </label>
          </>
          {children}
        </ThemeContext.Provider>
      </body>
    </html>
  );
}
